package com.botmaker.cli.release;

import org.junit.jupiter.api.Test;

import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

class DepsEnvTest {

    @Test
    void studioPinsFourAndTheTwoItDoesNotArePositions() {
        // Not an oversight in either direction: Studio has had no botmaker-sdk dependency since
        // 2026-09-02, and the toolkit is a PLUGIN's dependency, never the host's.
        assertEquals(List.of(Module.SHARED, Module.SESSION, Module.STUDIO_API, Module.PLUGIN_HOST),
                DepsEnv.upstreams(Module.STUDIO));
        assertFalse(DepsEnv.upstreams(Module.STUDIO).contains(Module.SDK));
        assertFalse(DepsEnv.upstreams(Module.STUDIO).contains(Module.PLUGIN_TOOLKIT));
    }

    @Test
    void theTwoModulesThatRecordNothingRecordNothing() {
        // studio-api pins nothing of ours; the archetype ships text whose versions are generation-time
        // properties, so there is no pin for a contract release to invalidate.
        assertFalse(DepsEnv.writes(Module.STUDIO_API));
        assertFalse(DepsEnv.writes(Module.PLUGIN_ARCHETYPE));
        assertFalse(DepsEnv.writes(Module.PILOT));
        assertThrows(ReleaseRefusal.class, () -> DepsEnv.text(Module.STUDIO_API, Map.of()));
    }

    @Test
    void theFileListsOnlyWhatThisModulePinsAndInTheFilesOwnOrder() {
        String text = DepsEnv.text(Module.SDK, Map.of(
                Module.SHARED, "v0.0.20",
                Module.SESSION, "v0.0.12",
                Module.STUDIO_API, "v0.0.4",
                Module.PLUGIN_TOOLKIT, "v0.0.5",
                // Not one of the SDK's pins: passed and ignored, so a caller cannot widen the file by
                // handing it more refs.
                Module.PLUGIN_HOST, "v0.0.5"));

        assertTrue(text.contains("""
                SHARED_TAG=v0.0.20
                SESSION_TAG=v0.0.12
                STUDIO_API_TAG=v0.0.4
                PLUGIN_TOOLKIT_TAG=v0.0.5"""), text);
        assertFalse(text.contains("PLUGIN_HOST_TAG"));
        assertFalse(text.contains("SDK_TAG"));
    }

    @Test
    void theHeaderSaysWhoReadsItAndWhereTheReasonIsWrittenDown() {
        String text = DepsEnv.text(Module.PLUGIN_TOOLKIT, Map.of(Module.STUDIO_API, "v0.0.4"));

        assertTrue(text.startsWith("# Generated by the umbrella release.sh — do not hand-edit"));
        assertTrue(text.contains("# The upstream refs this botmaker-plugin-toolkit release is built"
                + " against."));
        assertTrue(text.contains("-Dbotmaker.studioapi.version at build time."));
        // The pointer to why an exact ref rather than the newest tag, which is the decision that file
        // records and the one a reader will want.
        assertTrue(text.contains("botmaker umbrella's CLAUDE.md"));
        assertTrue(text.endsWith("STUDIO_API_TAG=v0.0.4\n"));
    }

    @Test
    void anUpstreamWithNoRefIsOmittedRatherThanWrittenEmpty() {
        // An empty value would be sourced by jitpack.yml as an empty -D, which resolves to nothing and
        // publishes a pom naming a dependency that cannot exist.
        String text = DepsEnv.text(Module.CLI, Map.of(Module.STUDIO_API, "v0.0.4"));

        assertTrue(text.contains("STUDIO_API_TAG=v0.0.4"));
        assertFalse(text.contains("PLUGIN_HOST_TAG"));
    }
}
